### ISSUE TITLE
Rewrite MongoPool to remove dependencies on other components and make it open source suitable

### ISSUE THREAD

**Issue by bogdanciobanu** [uberVU/mongo-pool#1]
## Need

``` gherkin
As a developer
I want a mechanism to manage multiple mongo connections to different clusters and map databases to connections 
So that I won't be forced to remember the host and the port and create a connection each time I want to work with a database on a different cluster and write those details in a single place
```
## Deliverables

``` gherkin
Scenario: Working with databases on multiple clusters
Given I have to work with some databases located on different clusters
  And I write connection information in a configuration file
When  I want to access a database
Then   I can access the wanted database based solely on it's name
```
## Solution

A class MongoPool that keeps internally a list with database information (host, port, read preference, database name).
When the user wants to access a database, all he has to do is mongopool.db_name. Behind the scene, it will create a connection to the correct cluster and return the database. To make it accessible as a simple attribute, the `__getattr__` method will be implemented.
#### TODO
- [ ] write test to check that the returned database is from the correct connection (check the host and port with the ones from the configuration)
- [ ] write test to check that "No such database" Exception is raised when trying to access a database that was not configured
- [ ] implement the first version in which the user can access databases via dot notation (it will work only with precise database names)
- [ ] replace the database name with a regexp pattern
