### ISSUE TITLE
Make MongoPool easier to inherit from

### ISSUE THREAD

**Issue by bogdanciobanu** [uberVU/mongo-pool#18]
## Need

``` gherkin
As a developer
I want to be able to use as much code as possible from an open-source project instead of rewriting it
So that I use it at its full potential, avoid reimplementing things and copy-paste code
```
## Deliverables

Make **getattr** method easier to be extended
## Solution

Break **getattr** logic in two parts. One that gets the connection to the cluster based on the name of the database to be accessed and one that returns the database from the cluster. This way, both can be modified to add functionality.
#### TODO
- [ ] write _get_connection_by_db_name method
- [ ] write _init_database method
- [ ] change **getattr** to use them
- [ ] write test to check that a connection is created only once for a cluster
#### Notes

This will enable us to use proper inheritance in private MongoPool
