### ISSUE TITLE
Rename mongopool to mongo_pool

### ISSUE THREAD

**Issue by bogdanciobanu** [uberVU/mongo-pool#25]
## Need

``` gherkin
As a developer
I want my packages to follow the naming convention
So that I can import them as expected
```
## Deliverables
- [ ] change package name to mongo_pool
#### Prerequisites
- [required dependency for identifying the problem, scope and then solution for this issue]
#### TODO
- [x] rename repository to mongo_pool https://help.github.com/articles/renaming-a-repository
- [x] change the name of the package in setup.py
- [x] change the url of the package
- [x] rename mongopool folder to mongo_pool
- [x] rename mongopool.py to mongo_pool.py
- [x] change imports in **init**.py to point to mongo_pool instead of mongopool
- [x] review documentation and replace mongopool with mongo_pool where needed
#### Notes

PR https://github.com/uberVU/mongo-pool/pull/26
